DROP TABLE COMPANY;
DROP SEQUENCE CNOSEQ;
INSERT INTO COMPANY VALUES(1,'kh','역삼','Y');
CREATE SEQUENCE CNOSEQ;
CREATE TABLE COMPANY(
	CNO NUMBER PRIMARY KEY,
	CNAME VARCHAR2(100) NOT NULL,
	CADDR VARCHAR2(500) NOT NULL,
	CYN VARCHAR2(10) NOT NULL,
	CONSTRAINT COMPANY_CYN_CHK CHECK(CYN IN('Y','N'))
);

SELECT * FROM COMPANY;
UPDATE USERBOARD SET USER_GRADE = 'user' WHERE user_id = 'admin1';
DROP TABLE USERBOARD;
SELECT * FROM USERBOARD;
CREATE TABLE USERBOARD(
	USER_ID VARCHAR2(100) PRIMARY KEY,
	USER_PW VARCHAR2(100) NOT NULL,
	USER_NAME VARCHAR2(100) NOT NULL,
	USER_EMAIL VARCHAR2(150) UNIQUE NOT NULL,	
	USER_BIRTH DATE NOT NULL,
	USER_GRADE VARCHAR2(20) NOT NULL,
	USER_SNS VARCHAR2(100) NOT NULL,
	USER_CONFIRM VARCHAR2(200) NOT NULL,
	USER_IMG VARCHAR2(1000) NULL,
	CNO NUMBER NOT NULL,
	
	CONSTRAINT USERBOARD_USER_CONFIRM_CHK CHECK(USER_CONFIRM IN('Y','N'))
);
ALTER TABLE USERBOARD ADD FOREIGN KEY (CNO) REFERENCES COMPANY(CNO);

SELECT * FROM USERBOARD WHERE USER_ID = 'bob';
UPDATE USERBOARD SET USER_GRADE = 'bob' WHERE USER_ID = 'bob';


INSERT INTO USERBOARD
VALUES('test','test','admin','os9397@naver.com','수원시 권선구 호매실동 GS아파트','01051818161','M', SYSDATE,'회장','x','Y','A',1);

SELECT * FROM BOBMANAGER WHERE USER_ID = 'test';

SELECT * FROM BOBMANAGER

INSERT INTO BOBMANAGER
VALUES(BMIDSEQ.NEXTVAL,'test','20190321','아침','짜장면','640','ZZAZANG');

INSERT INTO BOBMANAGER
VALUES(BMIDSEQ.NEXTVAL,'test','20190321','아침','햄버거','700','ZZAZANG');


INSERT INTO BOBMANAGER
VALUES(BMIDSEQ.NEXTVAL,'test','20190321','점심','짬뽕','550','ZZAZANG');
INSERT INTO BOBMANAGER
VALUES(BMIDSEQ.NEXTVAL,'test','20190321','점심','피자','800','ZZAZANG');



INSERT INTO BOBMANAGER
VALUES(BMIDSEQ.NEXTVAL,'test','20190321','저녁','탕수육','800','ZZAZANG');
INSERT INTO BOBMANAGER
VALUES(BMIDSEQ.NEXTVAL,'test','20190321','저녁','푸딩','240','ZZAZANG');


SELECT * FROM BOBMANAGER;

DELETE FROM BOBMANAGER WHERE USER_ID = 'test';





DROP SEQUENCE BOBIDSEQ;
DROP TABLE BOB;

CREATE SEQUENCE BOBIDSEQ;
CREATE TABLE BOB(
	BOB_ID NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(100) NOT NULL,
	BOB_DATE DATE NOT NULL,
	BOB_TYPE VARCHAR2(100) NOT NULL,
	BOB_MENU VARCHAR2(400) NOT NULL,
	BOB_KAL VARCHAR2(200) NOT NULL,
	BOB_IMG VARCHAR2(1000) NOT NULL
);
ALTER TABLE BOB ADD FOREIGN KEY (USER_ID) REFERENCES USERBOARD(USER_ID);


DROP SEQUENCE BMIDSEQ;
DROP TABLE BOBMANAGER;

CREATE SEQUENCE BMIDSEQ;
CREATE TABLE BOBMANAGER(
	BM_ID NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(100) NOT NULL,
	BM_DATE VARCHAR2(30) NOT NULL,
	BM_TYPE VARCHAR2(100) NOT NULL,
	BM_MENU VARCHAR2(400) NOT NULL,
	BM_KAL VARCHAR2(200) NOT NULL,
	BM_IMG VARCHAR2(1000) NOT NULL
);
ALTER TABLE BOBMANAGER ADD FOREIGN KEY (USER_ID) REFERENCES USERBOARD(USER_ID);
SELECT * FROM BOBMANAGER;
=======

--건의사항
DROP SEQUENCE SCOMMENT_seq;
DROP TABLE SCOMMENT PURGE;

DROP SEQUENCE SUGGEST_seq;
DROP TABLE SUGGEST PURGE;

CREATE TABLE SUGGEST(
	bno NUMBER PRIMARY KEY,
	writer VARCHAR2(100) NOT NULL,
	title VARCHAR2(1000) NOT NULL,
	content VARCHAR2(4000) NOT NULL,
	regDate DATE DEFAULT SYSDATE,
	viewCnt NUMBER DEFAULT 0
);
CREATE SEQUENCE SUGGEST_seq;

ALTER TABLE SUGGEST ADD FOREIGN KEY (USER_ID) REFERENCES USERBOARD(USER_ID);

CREATE TABLE SCOMMENT(
	bno NUMBER NOT NULL,
	rno NUMBER NOT NULL,
	writer VARCHAR2(100) NOT NULL,
	content VARCHAR2(4000) NOT NULL,
	regDate DATE DEFAULT SYSDATE,
	PRIMARY KEY(bno,rno)
);
alter table SUGGEST
	add constraint SUGGEST_bno foreign key(bno)
	references SUGGEST(bno) on delete cascade;
CREATE SEQUENCE SCOMMENT_seq; 

ALTER TABLE SCOMMENT ADD FOREIGN KEY (S_NO) REFERENCES SUGGEST(S_NO);
------------------------------------------------------------------

DROP SEQUENCE NNOSEQ;
DROP TABLE NOTICE;

CREATE SEQUENCE NNOSEQ;
CREATE TABLE NOTICE(
	N_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(100) NOT NULL,
	N_TITLE VARCHAR2(1000) NOT NULL,
	N_CONTENT VARCHAR2(4000) NOT NULL,
	N_DATE DATE NOT NULL,
	N_VIEW NUMBER NOT NULL
);
ALTER TABLE NOTICE ADD FOREIGN KEY (USER_ID) REFERENCES USERBOARD(USER_ID);

DROP SEQUENCE ROOMSEQ;
DROP TABLE CHATROOM;

CREATE SEQUENCE ROOMSEQ;
CREATE TABLE CHATROOM(
	CH_ROOMNO NUMBER PRIMARY KEY,
	CH_USERCNT NUMBER NOT NULL
);
ALTER TABLE CHATROOM ADD FOREIGN KEY (USER_ID) REFERENCES USERBOARD(USER_ID);


DROP SEQUENCE CHUSERSEQ;
DROP TABLE CHATUSER;

CREATE SEQUENCE CHUSERSEQ;
CREATE TABLE CHATUSER(
	CR_NO NUMBER PRIMARY KEY,
	CH_ROOMNO NUMBER NOT NULL,
	USER_ID VARCHAR2(100) NOT NULL,
	TARGET_ID VARCHAR2(100) NOT NULL
);
ALTER TABLE CHATUSER ADD FOREIGN KEY (CH_ROOMNO) REFERENCES CHATROOM(CH_ROOMNO);
ALTER TABLE CHATUSER ADD FOREIGN KEY (USER_ID) REFERENCES USERBOARD(USER_ID);

DROP SEQUENCE CHNOSEQ;
DROP TABLE CHAT;

CREATE SEQUENCE CHNOSEQ;
CREATE TABLE CHAT(
	CH_NO NUMBER PRIMARY KEY,
	CR_NO NUMBER NOT NULL,
	CH_ROOMNO NUMBER NOT NULL,
	USER_ID VARCHAR2(100) NOT NULL,
	CH_MSG VARCHAR2(1500) NOT NULL,
	CH_TIME DATE NOT NULL
);
ALTER TABLE CHAT ADD FOREIGN KEY (CH_USERNO) REFERENCES CHATUSER(CH_ROOMNO);
ALTER TABLE CHAT ADD FOREIGN KEY (CR_NO) REFERENCES CHATUSER(CR_NO);


--댓글 
DROP SEQUENCE myReply_seq;
DROP TABLE myReply PURGE;

--게시글
DROP SEQUENCE myBoard_seq;
DROP TABLE myBoard PURGE;

CREATE TABLE myBoard (
	bno NUMBER NOT NULL,
	title VARCHAR2(30) NOT NULL,
	content VARCHAR2(2000) NOT NULL,
	writer VARCHAR2(30) NOT NULL,
	regDate DATE default SYSDATE,
	viewCnt number default 0,
	primary key(bno)
);
CREATE SEQUENCE myBoard_seq;
SELECT * FROM MYBOARD;



CREATE TABLE myReply(
	bno number not null,
	rno number not null,
	content varchar2(2000) not null,
	writer varchar2(30) not null,
	regDate DATE default SYSDATE,
	primary key(bno,rno)
);

alter table myReply
	add constraint myReply_bno foreign key(bno)
	references myBoard(bno) on delete cascade;
	
CREATE SEQUENCE myReply_seq; 
