DROP TABLE TB_CUSTOMER PURGE;

CREATE TABLE TB_CUSTOMER(
	ID VARCHAR2(100) PRIMARY KEY,
	PASSWORD VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(100) NOT NULL
);

INSERT INTO TB_CUSTOMER VALUES('admin','1234','°ü¸®ÀÚ');

SELECT * FROM TB_CUSTOMER;